bind_addr = ":7777"
log_level = "info"
database_url = "admin:sf9RWMEBmWnn@/nix_db"

 [Tokens]
 accessSecret  = "access_secret_k"
 refreshSecret = "refresh_secret_k"

# accessLifetimeMinutes  = 5
# refreshLifetimeMinutes = 60


