bind_addr = ":7777"
log_level = "debug"
database_url = "kirill:Ya8eb2a3l@/nix_db"

# [Tokens]
# accessSecret  = "access_secret_k"
# refreshSecret = "refresh_secret_k"
#
# accessLifetimeMinutes  = 5
# refreshLifetimeMinutes = 60


